/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.karatsuba.newpackage;
import java.math.BigInteger;
/**
 *
 * @author JuanRicardo
 */


public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        box1 = new javax.swing.JTextField();
        box2 = new javax.swing.JTextField();
        box3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("KARATSUBA CALCULATOR");

        jButton1.setText("x");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Number 1");

        jLabel3.setText("Number 2");

        jLabel4.setText("Result");

        jLabel5.setText("Multiply");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(box1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                                .addComponent(box2)
                                .addComponent(box3)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        box3.setText(" ");
        int m = 0;
        String fn,fn1,fn2 = null,fnn,fn11,fn22 = null;
        
               
        fn=box1.getText();
        fnn=box2.getText();

try{ BigInteger error1 = new BigInteger (fn);
BigInteger error2 = new BigInteger (fnn);}
catch(NumberFormatException ex){
        	
    box3.setText("Error: Spaces, letters or special characters are not allowed, please try again...");}
         
        BigInteger yy0 = null;
        BigInteger xx0 = null;
       
        BigInteger cero = new BigInteger ("0");
        BigInteger bb = new BigInteger ("10");
        BigInteger bbb = new BigInteger ("10");
        BigInteger x = null;
        BigInteger y = null;
        BigInteger z2 = null;
        BigInteger z1 = null;
        BigInteger z0 = null;
        BigInteger resultado = null;
        
        if(fn.length()<fnn.length()){m=fn.length()/2;}
        else if(fn.length()>fnn.length()){m=fnn.length()/2;}
        else if(fn.length()==fnn.length()){m=fn.length()/2;}
         
            
        fn1=fn.substring(0,fn.length()-m); 
        if(m>0){fn2=fn.substring(fn.length()-m);}
             
        //x1=Integer.parseInt(fn1);
         BigInteger x1 = new BigInteger (fn1);
         
        if(m>0){
        //x0=Integer.parseInt(fn2);
        BigInteger x0 = new BigInteger (fn2);
        xx0=x0;}
        else{xx0=cero;}
       
        //bb=(int)Math.pow(10,m);
        bb=bb.pow(m);
        
        //bbb=(int)Math.pow(10,2*m);
        bbb=bbb.pow(2*m);
        
       //x=x1*bb+x0;
        x=x1.multiply(bb);
        
        x=x1.add(xx0);
        
        
        
        fn11=fnn.substring(0,fnn.length()-m);
        if(m>0){fn22=fnn.substring(fnn.length()-m);}
        
        
       
               
        //y1=Integer.parseInt(fn11);
        BigInteger y1 = new BigInteger (fn11);
        if(m>0){
            //y0=Integer.parseInt(fn22);
        BigInteger y0 = new BigInteger (fn22);
        yy0=y0;}
        else{yy0=cero;}
        
        //y=y1*bb+y0;
        y=y1.multiply(bb);
        y=y1.add(yy0);
        
        //z2=x1*y1;
        //z0=x0*y0;
        //z1=(x1+x0)*(y1+y0)-z2-z0;
        //resultado=z2*bbb+z1*bb+z0;
        //r=Integer.toString(resultado);
        z2=x1.multiply(y1);
        z0=xx0.multiply(yy0);
        BigInteger prod1 = x1.add(xx0);
        BigInteger prod2 = y1.add(yy0);
        BigInteger prod3 = prod1.multiply(prod2);
        z1=prod3.subtract(z2);
        z1=z1.subtract(z0);
        z1=z1.multiply(bb);
        
        resultado=z2.multiply(bbb);
        resultado=resultado.add(z0);
        resultado=resultado.add(z1);
        
        
             
        box3.setText(""+resultado);
               
        
                
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField box1;
    private javax.swing.JTextField box2;
    private javax.swing.JTextField box3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
